# Generated by Django 3.2.18 on 2023-03-05 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230225_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinrecipt',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.ingredient', verbose_name='Ингридиент'),
        ),
    ]
