# Generated by Django 3.2.18 on 2023-03-17 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Допустим ввод букв и символов из числа ".@+-_"', regex='[\\w.@+-_]+')], verbose_name='Уникальный юзернейм'),
        ),
    ]
