# Generated by Django 3.2.18 on 2023-03-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sucscribe',
            new_name='Subscribe',
        ),
    ]
