name: Foodgram app workflow

on: [push]

jobs:
  
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        ls
        pwd
        pip install -r backend/requirements.txt
    - name: Test with flake8
      run: |
        python -m flake8
  
  build_and_push_to_docker_hub:
    if: ${{ github.ref_name == 'master' || github.ref_name == 'main'}}
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest
          file: backend/Dockerfile


  send_message:
    name: Send message to Telegramm
    runs-on: ubuntu-latest
    needs: deploy
    steps:

    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} - Successful push repository ${{ github.event.repository.name }} in adress ${{ github.repositoryUrl }} did ${{ github.actor }}. Reason - ${{ github.event.commits[0].message }}. Commit in adress - https://github.com/${{ github.repository }}/commit/${{github.sha}}
